name: crva_app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - django=4.1
  - django-allauth
  - django-import-export
  - netcdf4
  - shapely
  - gdal
  - geos
  - earthengine-api
  - beautifulsoup4
  - psycopg2
  - gunicorn
  - pip
  - pip:
      - asgiref==3.8.0
      - djangorestframework
      - django-extensions
      - PyJWT
