name: crva_app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - django=4.1.*
  - django-allauth
  - django-import-export
  - gdal
  - geos
  - shapely
  - netcdf4
  - psycopg2
  - beautifulsoup4
  - earthengine-api
  - gunicorn
  - pip
  - pip:
      - djangorestframework==3.14.0
      - django-extensions==3.2.3
      - django-modeltranslation==0.18.11
      - PyJWT