# Generated by Django 4.1 on 2025-05-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scenario', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='hazard_rasters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
