# Generated by Django 4.1 on 2025-05-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_province_boundary'),
        ('hazard_layer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardlayer',
            name='hazard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebApp.hazard'),
            preserve_default=False,
        ),
    ]
