# Generated by Django 4.1 on 2025-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_layer', '0002_hazardlayer_hazard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardlayer',
            name='file',
        ),
        migrations.AddField(
            model_name='hazardlayer',
            name='geoserver_layer_name',
            field=models.CharField(default=1, help_text='e.g. crva:drought_2021_scenario1', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazardlayer',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hazardlayer',
            name='workspace',
            field=models.CharField(default='crva', max_length=100),
        ),
    ]
