# Generated by Django 4.1 on 2025-05-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.TextField()),
                ('adaptation_strategy', models.TextField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptations', to='WebApp.province')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChainHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_chains', to='WebApp.hazard')),
                ('value_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='WebApp.valuechain')),
            ],
            options={
                'unique_together': {('value_chain', 'hazard')},
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_organization',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='riskadaptation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.stage'),
        ),
        migrations.AddField(
            model_name='riskadaptation',
            name='vc_hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='WebApp.valuechainhazard'),
        ),
    ]
