# Generated by Django 4.1 on 2025-05-24 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_hazard_province_riskadaptation_stage_valuechain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
