# Generated by Django 4.1 on 2025-05-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_layer', '0003_remove_hazardlayer_file_and_more'),
        ('WebApp', '0003_province_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.hazard')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard_layer.hazardlayer')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.province')),
            ],
            options={
                'unique_together': {('province', 'year', 'hazard', 'layer')},
            },
        ),
    ]
