# Generated by Django 4.1 on 2025-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_layer', '0003_remove_hazardlayer_file_and_more'),
        ('WebApp', '0004_provincetimeseries'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provincetimeseries',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='provincetimeseries',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='provincetimeseries',
            unique_together={('province', 'year', 'hazard', 'layer', 'name')},
        ),
    ]
