# Generated by Django 4.1 on 2025-07-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_provincetimeseries_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='riskadaptation',
            name='adaptation_strategy_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.adaptationstrategy'),
        ),
        migrations.AddField(
            model_name='riskadaptation',
            name='risk_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.risk'),
        ),
    ]
