# Generated by Django 4.1 on 2025-07-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_adaptationstrategy_risk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskadaptation',
            name='adaptation_strategy',
        ),
        migrations.RemoveField(
            model_name='riskadaptation',
            name='risk',
        ),
    ]
