# Generated by Django 4.1 on 2025-08-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_remove_riskadaptation_adaptation_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('adaptation_strategies', models.ManyToManyField(blank=True, related_name='implementation_strategies', to='WebApp.adaptationstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_activities', models.TextField(blank=True, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=255, null=True)),
                ('implementers', models.TextField(blank=True, null=True)),
                ('resources_needed', models.TextField(blank=True, null=True, verbose_name='Resources / Investments Needed')),
                ('expected_outcomes', models.TextField(blank=True, null=True)),
                ('beneficiaries', models.TextField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='WebApp.implementationstrategy')),
            ],
        ),
    ]
