# Generated by Django 4.1 on 2025-08-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_implementationstrategy_implementationentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='hazard',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='hazard',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hazards', to='WebApp.component'),
        ),
        migrations.AlterUniqueTogether(
            name='hazard',
            unique_together={('component', 'name')},
        ),
    ]
