# Generated by Django 4.2.24 on 2025-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_seed_components'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hazard',
            unique_together={('component', 'name')},
        ),
        migrations.AddField(
            model_name='adaptationstrategy',
            name='description_en',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adaptationstrategy',
            name='description_pt',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='component',
            name='label_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='label_pt',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hazard',
            name='name_pt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='beneficiaries_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='beneficiaries_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='expected_outcomes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='expected_outcomes_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='implementers_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='implementers_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='proposed_activities_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='proposed_activities_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='resources_needed_en',
            field=models.TextField(blank=True, null=True, verbose_name='Resources / Investments Needed'),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='resources_needed_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Resources / Investments Needed'),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='timeframe_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='implementationentry',
            name='timeframe_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='implementationstrategy',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='implementationstrategy',
            name='title_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='description_en',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='description_pt',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='valuechain',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='valuechain',
            name='name_pt',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hazard',
            unique_together={('component', 'name_pt'), ('component', 'name_en'), ('component', 'name')},
        ),
    ]
