# Generated by Django 4.2.24 on 2025-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_alter_hazard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementationstrategy',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='implementationstrategy',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='implementationstrategy',
            name='title_pt',
            field=models.TextField(null=True),
        ),
    ]
